language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t iporat08/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true iporat08/react-test npm test -- --coverage

after_sucess:
  - docker build -t iporat08/multi-client ./client
  - docker build -t iporat08/multi-nginx ./nginx
  - docker build -t iporat08/multi-server ./server
  - docker build -t iporat08/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker
  - docker push iporat08/multi-client
  - docker push iporat08/multi-nginx
  - docker push iporat08/multi-worker
  - docker push iporat08/multi-server

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-2-809837503369
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
    
